adding histropedia page
uoe-dlam/nuxt-witches pull request #140
Opened 2024-09-20 11:12 UTC by rubyimrie

2024-10-16 09:14 UTC, Sephster requested changes

2024-10-16 09:14 UTC, Sephster commented on components/MainNavBar.vue
> +              name: "Histropedia Timeline",
I think most users won't know what Histropedia is so it is probably better to revert this to the original title and change the page filename accordingly. Thanks Ruby

2024-10-16 09:14 UTC, Sephster commented on pages/histropedia-timeline.vue
> +  <div style="height: 100%; min-height: 500px;">
Are there equivalent tailwind calls we can use here?

2024-10-16 09:50 UTC, rubyimrie commented on components/MainNavBar.vue
> +              name: "Histropedia Timeline",
done

2024-10-16 09:54 UTC, rubyimrie commented on pages/histropedia-timeline.vue
> +  <div style="height: 100%; min-height: 500px;">
done

2024-10-17 09:14 UTC, Sephster commented on components/MainNavBar.vue
> +              name: "Histropedia Timeline",
Thank you

2024-10-17 09:15 UTC, Sephster commented on pages/histropedia-timeline.vue
> +  <div style="height: 100%; min-height: 500px;">
Thanks Ruby. Looks good to me!

2024-10-17 09:15 UTC, Sephster approved these changes

2024-10-17 09:15 UTC, merged