embedding witch tour of edinburgh page
uoe-dlam/nuxt-witches pull request #165
Opened 2024-10-18 08:30 UTC by rubyimrie

2024-10-21 22:19 UTC, Sephster requested changes

2024-10-21 22:19 UTC, Sephster commented on pages/witch-tour-edinburgh.vue
There seems to be some overlapping issue. The Edinburgh Castle text is cut off at the top

![image](https://github.com/user-attachments/assets/ab6f0244-eb04-4838-b039-3167fefe3370)

2024-10-21 22:19 UTC, Sephster commented on pages/witch-tour-edinburgh.vue
Appreciate your hands might be tied a bit with this but I was wondering if the captions should be shown by default or maybe hidden then expanded with a link? If we go down this route, it would be nice to animate the hide/close. Thanks Ruby

2024-10-22 08:23 UTC, rubyimrie commented on pages/witch-tour-edinburgh.vue
this is something Ewan has created using a storymap tool someone has created, he fills in a google sheet and it creates this, have edited the google sheet and added some spacing

2024-10-22 08:24 UTC, rubyimrie commented on pages/witch-tour-edinburgh.vue
not sure if have capacity to do this with the google sheet

2024-10-22 08:56 UTC, Sephster commented on pages/witch-tour-edinburgh.vue
that's fixed it. Thank you!

2024-10-22 08:56 UTC, Sephster commented on pages/witch-tour-edinburgh.vue
ok no worries. Will leave as is. Thanks Ruby

2024-10-22 08:57 UTC, Sephster approved these changes

2024-10-22 11:55 UTC, merged